import { useEffect, useRef } from 'react'

export default function ShareReport({ readings, medicines, onClose }) {
  const printRef = useRef()

  function convertToF(t, u) {
    return u === 'C' ? +(t * 9 / 5 + 32).toFixed(1) : +t
  }

  function statusLabel(t, u) {
    const f = convertToF(t, u)
    return f >= 103 ? 'High fever' : f >= 100.4 ? 'Mild fever' : 'Normal'
  }

  function statusColor(t, u) {
    const f = convertToF(t, u)
    return f >= 103 ? '#c0003c' : f >= 100.4 ? '#8a6000' : '#00755a'
  }

  const peak = readings.length ? Math.max(...readings.map(r => convertToF(r.temperature, r.unit))) : 0
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  function handlePrint() {
    window.print()
  }

  async function handleWhatsApp() {
    const text = `*Defervescence Fever Report*\nGenerated: ${today}\n\nReadings: ${readings.length}\nPeak: ${peak}°F\n\n${readings.slice(-5).map(r => `${r.date_display} ${r.time_display}: ${r.temperature}°${r.unit}`).join('\n')}\n\nMedicines: ${medicines.slice(-5).map(m => `${m.name} ${m.dose || ''} — ${m.date_display} ${m.time_display}`).join('\n')}`
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`)
  }

  return (
    <>
      {/* Overlay */}
      <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 100, display: 'flex', flexDirection: 'column' }}>

        {/* Action buttons */}
        <div style={{ background: '#16161a', padding: '16px', display: 'flex', gap: '10px', alignItems: 'center', borderBottom: '1px solid rgba(255,255,255,0.07)' }}>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#6b6875', cursor: 'pointer', fontSize: '1rem', padding: '4px 8px' }}>✕</button>
          <span style={{ color: '#f0ede8', fontSize: '0.82rem', flex: 1 }}>Fever Report</span>
          <button onClick={handleWhatsApp} style={{ background: '#25D366', color: '#fff', border: 'none', borderRadius: '8px', padding: '8px 14px', fontSize: '0.75rem', cursor: 'pointer', fontWeight: '500' }}>
            WhatsApp
          </button>
          <button onClick={handlePrint} style={{ background: '#ff6b35', color: '#fff', border: 'none', borderRadius: '8px', padding: '8px 14px', fontSize: '0.75rem', cursor: 'pointer', fontWeight: '500' }}>
            Print / PDF
          </button>
        </div>

        {/* Report preview */}
        <div style={{ flex: 1, overflow: 'auto', padding: '20px' }}>
          <div ref={printRef} id="print-report" style={{ background: '#fff', borderRadius: '12px', padding: '32px', maxWidth: '600px', margin: '0 auto', fontFamily: 'Georgia, serif', color: '#111' }}>

            {/* Header */}
            <div style={{ borderBottom: '2px solid #111', paddingBottom: '16px', marginBottom: '24px' }}>
              <h1 style={{ fontSize: '1.6rem', margin: '0 0 4px', color: '#111' }}>Fever Report</h1>
              <p style={{ fontSize: '0.8rem', color: '#666', margin: 0, fontFamily: 'monospace' }}>Generated by Defervescence · {today}</p>
            </div>

            {/* Summary */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '16px', marginBottom: '28px' }}>
              {[
                { label: 'Peak Temperature', value: peak + '°F', color: peak >= 103 ? '#c0003c' : peak >= 100.4 ? '#8a6000' : '#00755a' },
                { label: 'Total Readings', value: readings.length },
                { label: 'Period', value: readings.length ? readings[0].date_display?.split(',')[0] + ' – ' + readings[readings.length - 1].date_display?.split(',')[0] : '—' },
              ].map(s => (
                <div key={s.label} style={{ background: '#f5f5f5', borderRadius: '8px', padding: '12px' }}>
                  <div style={{ fontSize: '1.2rem', fontWeight: '700', color: s.color || '#111' }}>{s.value}</div>
                  <div style={{ fontSize: '0.65rem', color: '#666', marginTop: '2px', fontFamily: 'monospace', textTransform: 'uppercase', letterSpacing: '0.08em' }}>{s.label}</div>
                </div>
              ))}
            </div>

            {/* Readings table */}
            <h2 style={{ fontSize: '0.9rem', fontFamily: 'monospace', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#666', marginBottom: '12px' }}>Temperature Readings</h2>
            <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '28px', fontFamily: 'monospace', fontSize: '0.82rem' }}>
              <thead>
                <tr style={{ borderBottom: '2px solid #111' }}>
                  <th style={{ textAlign: 'left', padding: '8px 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Date</th>
                  <th style={{ textAlign: 'left', padding: '8px 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Time</th>
                  <th style={{ textAlign: 'left', padding: '8px 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Temperature</th>
                  <th style={{ textAlign: 'left', padding: '8px 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Status</th>
                </tr>
              </thead>
              <tbody>
                {[...readings].reverse().map(r => (
                  <tr key={r.id} style={{ borderBottom: '1px solid #eee' }}>
                    <td style={{ padding: '8px 0' }}>{r.date_display}</td>
                    <td style={{ padding: '8px 0', color: '#666' }}>{r.time_display}</td>
                    <td style={{ padding: '8px 0', fontWeight: '700' }}>{r.temperature}°{r.unit}</td>
                    <td style={{ padding: '8px 0', color: statusColor(r.temperature, r.unit) }}>{statusLabel(r.temperature, r.unit)}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Medicines table */}
            {medicines.length > 0 && (
              <>
                <h2 style={{ fontSize: '0.9rem', fontFamily: 'monospace', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#666', marginBottom: '12px' }}>Medicines Given</h2>
                <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '28px', fontFamily: 'monospace', fontSize: '0.82rem' }}>
                  <thead>
                    <tr style={{ borderBottom: '2px solid #111' }}>
                      <th style={{ textAlign: 'left', padding: '8px 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Medicine</th>
                      <th style={{ textAlign: 'left', padding: '8px 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Dose</th>
                      <th style={{ textAlign: 'left', padding: '8px 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Date</th>
                      <th style={{ textAlign: 'left', padding: '8px 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Time</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[...medicines].reverse().map(m => (
                      <tr key={m.id} style={{ borderBottom: '1px solid #eee' }}>
                        <td style={{ padding: '8px 0', fontWeight: '700', color: '#c0003c' }}>{m.name}</td>
                        <td style={{ padding: '8px 0' }}>{m.dose || '—'}</td>
                        <td style={{ padding: '8px 0' }}>{m.date_display}</td>
                        <td style={{ padding: '8px 0', color: '#666' }}>{m.time_display}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            )}

            {/* Notes */}
            <h2 style={{ fontSize: '0.9rem', fontFamily: 'monospace', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#666', marginBottom: '8px' }}>Notes</h2>
            <div style={{ border: '1px solid #ddd', borderRadius: '6px', padding: '12px', minHeight: '60px', fontSize: '0.82rem', color: '#666', fontFamily: 'monospace' }}>
              Add notes before printing…
            </div>

            {/* Footer */}
            <div style={{ borderTop: '1px solid #ddd', marginTop: '24px', paddingTop: '12px', fontSize: '0.7rem', color: '#999', fontFamily: 'monospace', textAlign: 'center' }}>
              Generated by Defervescence · Track the fever. Watch it fall. · defervescence.vercel.app
            </div>

          </div>
        </div>
      </div>

      {/* Print styles */}
      <style>{`
        @media print {
          body > * { display: none !important; }
          #print-report { display: block !important; position: fixed; top: 0; left: 0; width: 100%; padding: 24px; border-radius: 0; }
        }
      `}</style>
    </>
  )
}